### ISSUE TITLE
Perhaps change Compliance.ps1 to Compliance.psm1 and use Import-Module

### ISSUE THREAD

**Issue by JasonFossen** [iadgov/Secure-Host-Baseline#12]
Hello IAD:

On the page for Compliance Checks:

   https://github.com/iadgov/Secure-Host-Baseline/blob/master/Compliance/README.md

Consider renaming the Compliance.ps1 script to Compliance.psm1 to make it a module file, then using Import-Module instead of dot-sourcing the script (just like for GroupPolicy.psm1). 

I haven't tested this change on Windows 10, but on Server 2016 it worked fine.

Also, on that page above, please consider adding a note that Nessus is not required to run the Test-Compliance function on a standalone machine, e.g., "The following instructions can be used to execute a compliance check locally. This does not require Nessus to be installed." I know this seems obvious, but I've had two students ask this question.

Happy New Years!
    Jason

**Comment by iadgovuser1** [comment]
Fixed in 08cb68a and b2708c1
