### ISSUE TITLE
SHB v10.0.2 (SDC 5.2) Deployment Error Code

### ISSUE THREAD

**Issue by vho823** [iadgov/Secure-Host-Baseline#19]
User getting SHB v10.0.2 errors during Deployment Summary, screenshot attached. Only changes mentioned in the guide were made to the Deployment Workbench (e.g. no new applications added, core applications were not modified) but received the following 2 errors. Need assistance with how to troubleshoot and what this return code means. 

Application SHB Core Required -DoD NIPR Certs returned an unexpected return code 60002
Application SHB Core Required -McAfee Virus Scan Enterprise returned an unexpected return code: 60002

![shb deployment errors](https://cloud.githubusercontent.com/assets/25176904/22024963/d8836ce2-dc99-11e6-8b3a-c2c0282804d2.PNG)

**Comment by iadgovuser1** [comment]
These types of questions are best posed in the SHB forum on forge.mil since that's where the SHB Framework developers communicate. You will need a CAC to access it: https://software.forge.mil/sf/projects/win10shb?uri=/sf/projects/win10shb

**Comment by vho823** [comment]
I can access this site but no longer see an SHB forum.

**Comment by iadgovuser1** [comment]
It is under the Discussion tab.

**Comment by iadgovuser1** [comment]
After you login, manually browse to https://software.forge.mil/sf/projects/win10shb?uri=/sf/projects/win10shb and I think you will need to "join" the SHB sub site before being able to see the forums. At least I think that's what I originally had to do.
