### ISSUE TITLE
README.md Unblock-File Command

### ISSUE THREAD

**Issue by JasonFossen** [iadgov/Secure-Host-Baseline#2]
Thanks for the great project!

Trivial thing: in the README.md file there is an example command to unblock files: 

[System.IO.FileInfo[]]@(Get-ChildItem -Path '.\Secure-Host-Baseline') -Recurse -Filter '\*.ps1' | Unblock-File**

Note that there is also at least one .psm1 file (CreateCIPolicy.psm1) that doesn't match your filter, and the two asterisks at the end (**) is a typo.

Also, the total number of files is small, so is there a reason not to use something simpler like:

cd <Path-To-Secure-Host-Baseline-Folder>
dir -path *.* -recurse | unblock-file

Thanks!

**Comment by iadgovuser1** [comment]
Yep, totally missed updating that when we added the Device Guard PowerShell code. I updated the command but I tend not to use aliases.
