### ISSUE TITLE
Issue #20 Still not resolved

### ISSUE THREAD

**Issue by onedererer** [iadgov/Secure-Host-Baseline#21]
[Issue #20](https://github.com/iadgov/Secure-Host-Baseline/issues/20) is still not resolved. The SecGuide.admx does not match the DISA Windows 10 STIG V1R7. Specifically, it is missing Pol_SecGuide_RemoveRunasdifferentuser.

**Comment by iadgovuser1** [comment]
The templates I pulled are from https://blogs.technet.microsoft.com/secguide/2016/10/17/security-baseline-for-windows-10-v1607-anniversary-edition-and-windows-server-2016/

I did a diff between those and the ones provided by the STIG zip file and they are definitely different. I should have this resolved soon but want to make sure I get the right official templates.

**Comment by onedererer** [comment]
Outstanding! I thank you for the timely response and working of these issues.
