### ISSUE TITLE
Image error

### ISSUE THREAD

**Issue by greencouch90210** [iadgov/Secure-Host-Baseline#26]
I'm getting an error when deoying the SHB VM image. I receive a message saying it was successfully deployed then it immediately crashes. Error is your operating system couldn't be loaded because The system registry is missing or corrupt. What am I doing wrong?

**Comment by iadgovuser1** [comment]
Questions like this are best asked in the SHB forums since that's where the SHB Framework Toolbox developers answer questions like this. You need a CAC to access:  https://software.forge.mil/sf/projects/win10shb?uri=/sf/projects/win10shb
