### ISSUE TITLE
README.md Loading instructions with path to SHB folder

### ISSUE THREAD

**Issue by JasonFossen** [iadgov/Secure-Host-Baseline#3]
Thanks for the great project!

Trivial issue:

In the "Loading the Code" section, step 6 is to cd into the SHB folder.

Later, in the "Applying The Policies" section, the command as shown is to "Invoke-ApplySecureHostBaseline -Path '.\Secure-Host-Baseline' ...", which will fail if the user is already in the SHB folder from step 6 above. 

This is trivial, and people with shell experience will easily figure it out, but PowerShell novices will get errors and struggle unnecessarily.

Thanks!

**Comment by iadgovuser1** [comment]
Nice catch. Fixed.
