### ISSUE TITLE
Errors after Toolbox initiation

### ISSUE THREAD

**Issue by bcane98** [iadgov/Secure-Host-Baseline#30]
I am working on a HP Z230 standalone with 8GB RAM and plenty of HDD space, but I just can't get around this initial error when I launch the Toolbox:

ERROR#1 
![Uploading ERROR_1.JPG…]()

> Importing the PowerShell module for Microsoft Deployment Toolkit.  Please wait...
> Updating the MDT Deployment Share.  Please wait...
> Update-MDTDeploymentShare : Exception has been thrown by the target of an invocation.
> At C:\SHB\Toolbox\CaptureSHBRef.ps1:100 char:1
> + Update-MDTDeploymentShare -path "$SHBDSID`:" -Force >$null
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Update-MDTDeploymentShare], TargetInvocationException
>     + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,Microsoft.BDD.PSSnapIn.UpdateDeploymentPoint
> 
> Creating virtual network switch.  Please wait...
> VSwitch check #1
> Virtual switch SHBInternalNetwork created successfully.
> Assigning static IP address to the virtual network adapter.  Please wait...
> 

ERROR#2
A connectuion to the reployment share (\\10.10.10.10\SHB-DEP$) couls not be made.
DHCP Lease was not obtained for any Networking device! Possible Cause: Check physical connection.
Retry or Cancel.... retry only repeats Error#2

**Comment by bcane98** [comment]
Error #1 by turning FIPS off... still stuck on Error#2

**Comment by iadgovuser1** [comment]
Questions like this are best suited to being asked in the SHB forums where the SHB ToolBox Framework developers answer questions.

https://software.forge.mil/sf/projects/win10shb?uri=/sf/projects/win10shb

I'm pretty sure this error was reported there recently. Yep: https://software.forge.mil/sf/discussion/do/listPosts/projects.win10shb/discussion.general_discussion.topc12734

Unfortunately there have been no replies yet.

Are you doing this on a STIGed system? Ironically using the SHB Framework Toolbox on an STIGed system isn't supported.

**Comment by bcane98** [comment]
Yup.. started there, that's my post, so then I turned here... I think you answered it though.

**Comment by iadgovuser1** [comment]
FYI, I sent the forum thread to the SHB tools team.

**Comment by iadgovuser1** [comment]
I'm closing this out. Feel free to re-open and comment if you don't hear from the SHB tools team.
