### ISSUE TITLE
Error running Invoke-ApplySecureHostBaseline: "The variable cannot be validated because the value is not a valid value for the ToolPath variable"

### ISSUE THREAD

**Issue by juangranados** [iadgov/Secure-Host-Baseline#33]
Hello! 

First of all, thanks for this amazing tool, I am getting an error when running Invoke-ApplySecureHostBaseline on a Domain Controller running Windows Server 2008 R2 with Powershell 5. 

When I run the command: Invoke-ApplySecureHostBaseline -Path '.\Secure-Host-Baseline' -PolicyNames 'Adobe Reader'

The error says: "The variable cannot be validated because the value is not a valid value for the ToolPath variable"

![shberror](https://cloud.githubusercontent.com/assets/6050403/25612409/e5bd9bba-2f2a-11e7-8583-162563df12ef.png)

Thanks!

**Comment by beems** [comment]
Juan,

Check your group policy objects in Group Policy Management. It is likely that the group policy was created despite that error. Note: We had the same issue, I just never actually made it to posting the problem back here.

**Comment by iadgovuser1** [comment]
-ToolPath is an optional argument that isn't required  on a domain joined system but it is required on a non-domain joined system. I believe there is a bug in the code. I need to change where I do path resolution of $ToolPath to after the check to see if it was specified or not. There are at least 2 functions where I think I need to make a change.

**Comment by juangranados** [comment]
beems you are right! GPO objects were created after running the command. Thanks!
Thanks iadgovuser1 for this tool!

Regards!

**Comment by iadgovuser1** [comment]
I attempted a guess at a fix in c714219 so let me know if that resolves this. If it doesn't, then re-open this bug and I will take a closer look.

**Comment by juangranados** [comment]
@iadgovuser1 

I was able to run "Invoke-ApplySecureHostBaseline -Path '.\Secure-Host-Baseline' -PolicyNames 'Adobe Reader','AppLocker','Certificates','Chrome','EMET','Internet Explorer','Office 2013','Office 2016','Windows','Windows Firewall'"

Whit no errors. Bug resolved!

**Comment by iadgovuser1** [comment]
@juangranados 

Awesome. Thanks for reporting the bug.

**Comment by iadgovuser1** [comment]
Note to self: the issue boiled down to that any function that had ToolPath as optional needed to move the path resolution from the beginning of the function (where it has no real value) to after the checks for when it is required. Then it will be guaranteed to have a value. Invoke-ApplySecureHostBaseline, New-PolicyObjectBackup, and Import-PolicyObject all had ToolPath as optional.
