### ISSUE TITLE
Instructions to uninstall or remove a policy

### ISSUE THREAD

**Issue by kewubenduben** [iadgov/Secure-Host-Baseline#38]
Is there a documentation somewhere on how to revoke the policy after applied? or modify them?

Use case:

   I'm a home single-user only, I tested this SHB policy by following the instructions on README. After applying the policy, I've had some features that I'd like to reset/cancel and even fully disable the SHB so I can re-use my workstation just like before.

**Comment by iadgovuser1** [comment]
(U) Good question. This might be another version of #27. See this comment for more information: https://github.com/iadgov/Secure-Host-Baseline/issues/27#issuecomment-300029847

(U) At some point we are going to make an option that uses PowerShell and/or PowerShell DSC to apply settings that would be much easier to revert.

**Comment by jeffschulman** [comment]
Convert GPO templates to PowerShell DSC: https://4sysops.com/archives/convert-group-policy-to-powershell-dsc-with-admxtodsc/

**Comment by iadgovuser1** [comment]
@jeffschulman Thanks for the link. https://github.com/gpoguy/ADMXToDSC looks worth investigating.

**Comment by jeffschulman** [comment]
No problem. I'd really like to get a solid DSC config for server core/nano, as they're both allowed per the wording of the Server 2016 STIG. I may start working a local effort if I can free up some cycles.

**Comment by iadgovuser1** [comment]
@jeffschulman In case you aren't aware of these resources (you probably already are):
* https://blogs.msdn.microsoft.com/powershell/2016/05/09/new-security-cmdlets-in-nano-server/
* https://blogs.msdn.microsoft.com/powershell/2016/05/20/new-group-policy-cmdlets-for-nano-server/
* https://blogs.msdn.microsoft.com/powershell/2017/02/21/managing-security-settings-on-nano-server-with-dsc/

We currently have someone investigating the DSC route since we also need it for systems that are unmanaged and LGPO has some disadvantages that DSC doesn't (plus you can then use https://github.com/Microsoft/DSCEA ). No ETA on that work as it literally just started and it is lower priority compared to other projects in our list. It is being worked on, but I'm not sure when it will be done.

**Comment by JasonFossen** [comment]
[ResourceExample-Service.ps1.txt](https://github.com/iadgov/Secure-Host-Baseline/files/1226616/ResourceExample-Service.ps1.txt)

I started a DSC config for managing services startup settings if you want to use it (attached).  I plan to do more (I teach a course for the Army that has SHB and DSC modules) and will happily share those files too when I write them -- however, DSC may be changing with PowerShell 6.0, especially on Nano.  This Microsoft post about the future of Windows PowerShell vs. PowerShell Core is something to consider before doing a lot of work on a DSC implementation of the SHB:

https://blogs.msdn.microsoft.com/powershell/2017/07/14/powershell-6-0-roadmap-coreclr-backwards-compatibility-and-more/

It wouldn't be fun to invest a lot of effort in a DSC config for the SHB, then have Microsoft make changes that would require a major rewrite.  The article above, for example, says that development on "Windows PowerShell" with the Full .NET Framework has halted, and that all future work is going into "PowerShell Core" with the Core .NET Framework.  This will likely have an impact on which DSC resource modules may be used for a DSC SHB.  And at the PowerShell EU Conference a few months ago, a PowerShell manager at Microsoft (Bruce Payette) said that DSC is going to change: 

https://www.youtube.com/watch?v=ds11jTyBHiE&list=PLsMyEEBHQgbSZAkAnnjenRtpo5RUm30WW&index=41

You're probably aware of these things already, but I just wanted to give a friendly heads-up, just in case, before a lot of work goes into DSC for the SHB.  If you have a contact inside Microsoft, it might be nice to get some guidance for 2018/2019.

Cheers,
  Jason

**Comment by jeffschulman** [comment]
@JasonFossen @iadgovuser1  great info, thanks!

**Comment by iadgovuser1** [comment]
Ran across this today (ConvertFrom-GPO): https://github.com/Microsoft/BaselineManagement

**Comment by iadgovuser1** [comment]
@JasonFossen I'm sure you've read this by now: https://blogs.msdn.microsoft.com/powershell/2017/09/12/dsc-future-direction-update/

**Comment by JasonFossen** [comment]
Hi iadgovuser1, yes, thanks for the link though, it's exactly what I was concerned about.  I hope your group didn't go too far down the DSC road for the SHB.

**Comment by iadgovuser1** [comment]
@JasonFossen "Luckily" the person working on this had another project take higher priority so we haven't committed much yet. #41 is tracking this now.
