### ISSUE TITLE
README.md The GPOs which are backed up

### ISSUE THREAD

**Issue by JasonFossen** [iadgov/Secure-Host-Baseline#4]
Thanks for the great project!

Trivial issue:

In the "Applying the Policies" section it says the function will "Make a backup copy of existing Group Policy Objects", which implies all GPOs.  However, it should say something like "Make a backup copy of existing Group Policy Objects previously created for the Secure Host Baseline" because it does not back up all existing GPOs.

The first time the Invoke-ApplySecureHostBaseline is run, the %UERPROFILE%\Desktop\Backup_yyyyMMddHHmmss folder will still be created, but its subdirectories will be empty because the SHB GPOs don't exist yet.  The backup folder shouldn't be created unless there are SHB GPOs to back up.  

Thanks!

**Comment by iadgovuser1** [comment]
Fixed the working to hopefully make it more clear.

Also changed the script to delete a Backup_yyyyMMddHHmmss folder if it or its subfolders don't contain any files (no GP backup performed or no -UpdateTemplates option used).
