### ISSUE TITLE
Group Policy Local

### ISSUE THREAD

**Issue by Pitico** [iadgov/Secure-Host-Baseline#40]
I'm trying to set some local policies for chrome, but it does not seem to work, I'm trying to set the start page, chrome seems to ignore locally defined policies, do you have any idea what that might be?

**Comment by iadgovuser1** [comment]
@Pitico How are you configuring the policies? If you are just creating the registry values directly, then Chrome will ignore them. As long as the Chrome Group Policy templates are on your system, I've had no issues using the Group Policy Object Editor via MMC on the local system and configuring policies that way.
