### ISSUE TITLE
Default to Smart Card Win10 Build 1607

### ISSUE THREAD

**Issue by jace5869** [iadgov/Secure-Host-Baseline#45]
Using 1607 in a Citrix App Layering VDI setting and we've tried different combinations of trying to get Windows to default to Smart Card.

When turning off Show Last User we get Other User, and from this screen password options are only defaulting, despite setting Default Credential Provider for the Smart Card Provider.

We've even had issues when setting Enforce Smart Card it will still not default to it, and you still have to select sign-in options and choose a smart card.

We've also tried with DoD configuration set in Local GP, but that doesn't seem to change the behavior any. Is it needed to be set?
Does ActivClient use a different provider than the Microsoft one?

On the Citrix side of things, we've tried having ActivClient in OS, Platform and App Layers with no noticeable changes.

**Comment by jokezone** [comment]
Yes, ActivClient uses a different provider. BUT in my experience it still doesn't 100% fix the issue. It seems to be a problem that ActivClient, not Microsoft, needs to fix. VERY annoying issue. I hope it can be resolved soon.

**Comment by jace5869** [comment]
Do you know what provider we should set the default credential to?

**Comment by jokezone** [comment]
After you log into the system running ActivClient v7, check the LastLoggedOnProvider value under HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\SessionData. That will be the provider GUID used by ActivClient. As I said, this provider has been hit or miss for us. I just read a response on this thread from August 2017 stating that disabling the unwanted providers may achieve the results we want (smart card always being the default). https://social.technet.microsoft.com/Forums/en-US/7cbc01cd-a7ba-4595-a9de-da4286b9530e/how-to-set-smart-card-as-default-login-provider-on-windows-10

**Comment by iadgovuser1** [comment]
As far as I know, you can't set a default provider that will display on the screen. Windows' behavior was changed. Previous registry hacks don't work anymore. https://github.com/iadgov/Secure-Host-Baseline/tree/master/ActivClient#configuring-the-smart-card-credential-provider-as-the-default-logon-credential-provider contains information about this: _Smart card logon will be the default logon prompt once a user has logged into the system at least one time using a smart card. If the **Interactive Logon: Do not display last username** Group Policy setting is enabled, then a username and password prompt will always be the default logon prompt ([1](https://support.microsoft.com/en-us/help/2741622),[2](https://community.spiceworks.com/topic/post/4992568)). The **Interactive logon: Require smart card** Group Policy setting can be used to force the smart card credential provider to be the default logon prompt, but then only smart card logons are allowed._
