### ISSUE TITLE
Policies that block removeable storage access

### ISSUE THREAD

**Issue by jace5869** [iadgov/Secure-Host-Baseline#46]
Are there any policies that block or interfere with access to removable storage, specially on VMs?

Using Citrix AppLayering that utilizes a  mini-filter driver to capture changes and write to a vdisk and something might be blocking this. Are there any policies that might be causing this?

**Comment by iadgovuser1** [comment]
Windows has the general ability to block removable storage ([1](https://technet.microsoft.com/en-us/library/cc730808(v=ws.10).aspx), [2](https://technet.microsoft.com/en-us/library/cc730808(v=ws.10).aspx)), but there's nothing in the SHB group policies that configure those policies.
