### ISSUE TITLE
Win10 SHB disabling 64-bit option on VirtualBox

### ISSUE THREAD

**Issue by kentecho** [iadgov/Secure-Host-Baseline#47]
- Operating System: Windows10 Secure Host Baseline          

- Issue: Win10 SHB security blocking virtualization for Oracle VirtualBox

Steps already taken to fix issue:

 
1.Booted into BIOS and enabled Virtualization Technology (VTx), Virtualization Technology for Directed I/O (VTd), and Trusted Execution Technology (TXT) and SAVED

2.On desktop I have completely disabled Hyper-V

3.The option for 64-bit showed up BUT when computer restarted the option no longer existed and all Virtual Machines created under 64-bit were converted into 32-bit and rendered useless

 

None of the BIOS settings have changed and Hyper-V is still disabled yet the only option from Oracle VirtualBox is 32-bit when attempting to create a Virtual Machine.

**Comment by zagarjr** [comment]
Try installing VirtualBox using "Run as Administrator"...  Things don't seem to work right when I install under my normal user account even though I'm in the administrators group.

**Comment by iadgovuser1** [comment]
Check that hyper is not set to launch with bcdedit /enum /v

- https://derekgusoff.wordpress.com/2012/09/05/run-hyper-v-and-virtualbox-on-the-same-machine/

- https://www.virtualbox.org/ticket/12350

**Comment by iadgovuser1** [comment]
I'm closing this out since it isn't really an SHB issue.
