### ISSUE TITLE
Media Deployment Issue

### ISSUE THREAD

**Issue by lflane77** [iadgov/Secure-Host-Baseline#66]
When following DOD SHB Operations Guide for Win 10.4.x: Section 4.1: Step 5: Rules Tab;  
If one copies the CustomSettings.ini file with minor changes from the default, mostly Orginizational Branding changes the image fails. The image fails at the SkipLocaleSelection with the UILanguage variable blank. Even though the variable is defined in the Rules as SkipLocaleSelection = Yes and UILanguage = EN-US. The variable TaskSequenceID= SHB-10N-DEP.
Now if I change the variable TaskSequenceID to equal "SHB-10N-REF" the load will commence and complete but all the Orginizational Branding is lost. 
Please advise on what I may have missed or need to look for so that I can have this image run correctly. Thank you in advance.

**Comment by iadgovuser1** [comment]
Hi @lflane77,

This question is best addressed by the SHB Framework developers who are active on the project page that is part of forge.mil. You will need a CAC to access https://software.forge.mil/sf/projects/win10shb
