### ISSUE TITLE
How to activate SHB on Win10 Enterprise without network?

### ISSUE THREAD

**Issue by patboyle14** [iadgov/Secure-Host-Baseline#68]
Hi,

We're looking to deploy this image in an existing environment without network connectivity. Has anyone had experience with activating this image (built off of Win10 Enterprise) with a Win10 Enterprise "Upgrade" key from Microsoft Volume Licensing Center, and were you able to do over-the-phone activation? If so, has that worked for you? If not, what did you use instead to get this to work?

Thank you!

**Comment by iadgovuser1** [comment]
This ultimately depends on what type of media is being used. I believe there is separate volume licensed media that needs to be downloaded from the Microsoft Volume Licensing Service Center. I believe both current version and upgrade version media need to be from the VLSC. I don't know much about licensing so I could be way off. You might want to look into using KMS: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn502531(v=ws.11)
