### ISSUE TITLE
Issue with SCR3310v2 reader

### ISSUE THREAD

**Issue by johnlinton** [iadgov/Secure-Host-Baseline#7]
I am trying to get the SHB to work in my enclave.  

I have a dell OptiPlex 7040 which is apparently supported according to the IASE links to Dell.  Everything works (including the 7040 drivers) except for the CAC reader.  No matter what I try, I cannot get SHB win 10 to recognize the reader.  Upon bootup,  Activeclient complains that it can't find a CAC reader. Device manager gives me an ! mark for "SCR3310 USB Smart Card Reader".  I have tried manually installing the driver from MilitaryCAC, and that doesn't help.  Tried deleting the driver unplugging and plugging it back in to let windows install the driver.  Installing other drivers doesn't help as it says that the existing driver is the "best" driver.

We have no problem with our existing Windows 7 machines with these readers.  I even tried a working reader from another machine to rule out a physical defect.  It appears to be an issue with WIN 10 SHB and the reader.

Support would be appreciated!

**Comment by gnesto** [comment]
Try using the Microsoft driver.
Change in device manager by right clicking on the object > “Update Driver” > “Browse my computer” > “Let me choose...” > “Microsoft smart card driver”.

**Comment by johnlinton** [comment]
Works like a charm!!!  Thanks for the awesomely quick response!!

**Comment by johnlinton** [comment]
BTW, is this section only for bugs?  Where can I go for questions?  For some reason the IASE site lists assistance by Branch.  When I called my branch at the number provided by IASE, the support desk didn’t know why I was not using the AF Desktop instead of the DoD SHB and told me they couldn’t help me with it.

 

For instance, how do I inject registry changes (for example) changing netbanner status or how do I configure the deployment to use the Microsoft smart card driver.  I would use the virtual machine, but every time I try to run it after the first time, it gives me the error 0xc000000f, in recovery mode.  Must I implement my changes before the initial session ends?

 

Thanks.  Happy Holiday!

**Comment by iadgovuser1** [comment]
@johnlinton 

Yep, using the built-in smart card driver is the workaround.

You can also post questions to the SHB forums at https://software.forge.mil/sf/projects/win10shb?uri=/sf/projects/win10shb as long as you have a CAC. The types of implementation specific questions you have are best posed in the community SHB forum.
